"""Example: Using plugins to customize the research pipeline.

Plugins let you hook into various stages of the research process
to transform queries, filter sources, post-process results, etc.
"""

from deepworm import DeepResearcher
from deepworm.config import Config
from deepworm.plugins import PluginManager


def main():
    pm = PluginManager()

    # -----------------------------------------------------------
    # Hook 1: transform_queries – rewrite generated search queries
    # -----------------------------------------------------------
    @pm.hook("transform_queries")
    def add_year_filter(queries: list[str]) -> list[str]:
        """Append '2024' to every query for recency."""
        return [f"{q} 2024" for q in queries]

    # -----------------------------------------------------------
    # Hook 2: filter_source – decide which pages to keep
    # -----------------------------------------------------------
    @pm.hook("filter_source")
    def block_ads(url: str, title: str) -> bool:
        """Skip known ad-heavy or low-quality domains."""
        blocked = ["pinterest.com", "quora.com", "medium.com"]
        return not any(d in url for d in blocked)

    # -----------------------------------------------------------
    # Hook 3: post_analysis – enrich or rewrite analysis text
    # -----------------------------------------------------------
    @pm.hook("post_analysis")
    def tag_analysis(analysis: str) -> str:
        """Prefix each analysis with a tag for traceability."""
        return f"[VERIFIED] {analysis}"

    # -----------------------------------------------------------
    # Hook 4: post_report – transform the final report
    # -----------------------------------------------------------
    @pm.hook("post_report")
    def add_disclaimer(report: str) -> str:
        """Append a disclaimer to every report."""
        disclaimer = (
            "\n\n---\n"
            "*This report was generated by an AI research assistant. "
            "Always verify critical information from primary sources.*"
        )
        return report + disclaimer

    # -----------------------------------------------------------
    # Run with plugins
    # -----------------------------------------------------------
    config = Config.auto()
    researcher = DeepResearcher(config=config, plugins=pm)

    report = researcher.research("Latest trends in renewable energy")
    print(report)


if __name__ == "__main__":
    main()
