
"""DeepWorm - AI-powered deep research agent."""

import logging

__version__ = "1.5.0"

from .annotations import AnnotationSet, AnnotationType, annotate_report, auto_annotate, extract_annotations
from .async_api import AsyncResearcher, async_research
from .audit import AuditAction, AuditEntry, AuditLevel, AuditLog, AuditPolicy, AuditReport, create_audit_log, strict_audit_policy, minimal_audit_policy
from .batch import BatchConfig, BatchResult, BatchStatus, BatchTask, create_batch, run_batch
from .caching import Cache, CacheEntry, CacheStats, ComputeCache, EvictionPolicy, TieredCache, cache_key, create_cache, create_compute_cache, create_tiered_cache, memoize
from .chain import research_chain
from .cli_helpers import CLIArg, CLICommand, Color, OutputFormat, ProgressBar, Spinner, Verbosity, blue, bold, colorize, create_progress_bar, create_spinner, cyan, dim, draw_box, format_duration, format_help, format_key_value, format_list, format_percentage, format_size, format_table_simple, green, indent_text, pad_left, pad_right, parse_args, red, supports_color, truncate, yellow
from .compliance import ComplianceIssue, ComplianceReport, IssueCategory, Severity, StyleGuide, check_compliance, create_style_guide, academic_style_guide, technical_style_guide
from .concurrency import AtomicCounter, AtomicValue, Debouncer, Once, PoolStats, Task, TaskQueue, TaskResult, TaskStatus, Throttle, WorkerPool, WorkerState, create_atomic, create_counter, create_task_queue, create_worker_pool, parallel_map
from .credibility import CredibilityReport, CredibilityScore, score_source, score_sources
from .crossref import CrossRefIndex, CrossRefTarget, build_crossref_index, inject_crossrefs, generate_list_of_figures, generate_list_of_tables
from .data_pipeline import BatchResult as PipelineBatchResult, DataPipeline, ErrorStrategy, PipelineResult, PipelineStatus, Stage, StageResult, StageStatus, ValidationResult as DataValidationResult, ValidationRule, batch_process, chunk, create_pipeline as create_data_pipeline, create_validation_rule, distinct, fan_in, fan_out, filter_data, flatten, group_by, map_data, reduce_data, validate_data
from .diagnostics import CheckCategory, CheckResult, DiagnosticReport, DependencyStatus, EnvironmentInfo, HealthStatus, ProfileResult, Profiler, check_dependencies, collect_environment, create_profiler, quick_check, run_diagnostics, self_test
from .events import Event, EventEmitter, EventType
from .exceptions import (
    APIKeyError,
    ConfigError,
    ContentExtractionError,
    DeepWormError,
    ModelNotFoundError,
    NetworkError,
    ProviderError,
    RateLimitError,
    SearchError,
    SessionError,
)
from .export import ExportFormat, ExportOptions, ExportResult, batch_export, export_report
from .footnotes import FootnoteResult, add_footnotes, merge_footnotes, renumber_footnotes, strip_footnotes
from .formatter import EmphasisStyle, FormatOptions, FormatResult, ListStyle, TableAlignment, add_heading_ids, add_language_labels, create_format_options, ensure_blank_lines_around_headings, format_document, format_table, normalize_blockquotes, normalize_code_fences, normalize_emphasis, normalize_lists, sort_list
from .glossary import Glossary, GlossaryEntry, extract_glossary, inject_glossary
from .graph import Edge, EdgeType, GraphStats, KnowledgeGraph, Node, create_graph, extract_concept_graph, extract_link_graph, merge_graphs
from .history import HistoryEntry
from .hooks import HookContext, HookEntry, HookRegistry, HookResult, HookStage, Pipeline, PipelineResult, create_middleware, create_pipeline, get_global_registry, hook
from .http_middleware import MiddlewarePhase, RequestMethod, Request, Response, MiddlewareEntry, MiddlewareStack, RequestLog, RequestLogger, header_injection, timeout_middleware, retry_middleware, auth_middleware, content_type_middleware, user_agent_middleware, create_response, create_request, create_middleware_stack, create_logger
from .i18n import TranslationEntry, TranslationCatalog, LanguageDetection, detect_language, extract_translatable, create_catalog, merge_catalogs
from .keywords import Keyword, KeywordResult, extract_keywords, extract_tags
from .languages import Language, get_language, list_languages
from .notion import NotionBlock, NotionPage, export_notion_json, markdown_to_notion
from .outline import OutlineSection, ReportOutline, generate_outline, outline_from_report
from .planner import ResearchPlan, generate_plan, estimate_complexity
from .progress import ProgressSnapshot, ProgressTracker, ResearchStage
from .protocols import NOTHING, Configurable, Disposable, Either, Err, Identifiable, Lazy, Left, Nothing, Ok, Option, Pair, Renderable, Result, ResultStatus, Serializable, Some, Validatable, err, is_callable, is_dict_like, is_list_like, is_non_empty_string, is_numeric, is_renderable, is_serializable, is_validatable, left, nothing, ok, pair, right, safe_bool, safe_float, safe_int, safe_str, some, try_result
from .rate_limiter import LimiterStrategy, LimitAction, RateLimitInfo, RateLimitStats, TokenBucket, SlidingWindow, FixedWindow, KeyedRateLimiter, rate_limit, RateLimitExceeded, create_token_bucket, create_sliding_window, create_fixed_window, create_keyed_limiter
from .readability import ReadabilityResult, analyze_readability
from .references import Reference, Bibliography, extract_references, create_reference, inject_bibliography, merge_bibliographies
from .researcher import DeepResearcher
from .revisions import Revision, Change, RevisionDiff, RevisionHistory, compute_diff, create_revision, create_history, track_changes, merge_revisions
from .schema import DocumentSchema, FieldType, SchemaField, SectionRule, ValidationError as SchemaValidationError, ValidationResult as SchemaValidationResult, create_schema, report_schema, article_schema
from .scoring import QualityScore, score_report
from .security import ContentPolicy, SecurityFinding, SecurityReport, ThreatLevel, ThreatType, check_path_traversal, constant_time_compare, content_hash, detect_pii, detect_secrets, extract_urls, generate_token, mask_secret, redact_text, relaxed_policy, sanitize_html, sanitize_markdown, scan_content, strict_policy, validate_url
from .sentiment import SentimentScore, SentimentReport, ToneAnalysis, analyze_sentiment, analyze_tone, analyze_report_sentiment, sentiment_diff
from .serialization import Format, SerializationResult, DeserializationResult, to_json, from_json, to_yaml, from_yaml, to_csv, from_csv, to_xml, from_xml, to_markdown_table, from_markdown_table, detect_format, convert, serialize, pretty_json, minify_json
from .similarity import SimilarityResult, compare_texts, cosine_similarity, detect_plagiarism, find_similar
from .statistics import TextStatistics, ComparisonResult, compute_statistics, compare_statistics, vocabulary_analysis, section_statistics, reading_level
from .summary import Summary, extract_key_findings, extract_topics, summarize
from .template_engine import RenderResult, TemplateContext, TemplateError, Token, TokenType, comparison_template, create_context, extract_variables, list_filters, render_template, report_template, validate_template
from .testing_utils import AssertionMode, TestFixture, MockCall, MockFunction, MockSequence, Snapshot, SnapshotStore, TimingResult, create_fixture, create_mock, create_sequence, sample_markdown, sample_research_data, sample_config, assert_markdown_valid, assert_contains_all, assert_json_valid, assert_word_count_range, assert_no_duplicates, create_snapshot_store, time_execution, assert_fast
from .timeline import Timeline, TimelineEvent, extract_timeline, create_timeline, compare_timelines
from .toc import TocEntry, TableOfContents, extract_toc, generate_toc, inject_toc, merge_tocs
from .transform import TransformChain, TransformChainResult, TransformResult, TransformType, cleanup_transform, create_transform_chain, extract_section, find_replace, find_replace_batch, fix_indentation, normalize_headings, normalize_links, normalize_whitespace, remove_section, reorder_sections, strip_comments, strip_html, to_sentence_case, to_title_case, wrap_text
from .validator import ValidationResult, validate_topic
from .wordcloud import WordFrequency, WordCloudData, generate_word_cloud, compare_word_clouds, tfidf_cloud

__all__ = [
    "APIKeyError",
    "AnnotationSet",
    "AnnotationType",
    "AssertionMode",
    "AsyncResearcher",
    "AtomicCounter",
    "AtomicValue",
    "AuditAction",
    "AuditEntry",
    "AuditLevel",
    "AuditLog",
    "AuditPolicy",
    "AuditReport",
    "BatchConfig",
    "BatchResult",
    "BatchStatus",
    "BatchTask",
    "Bibliography",
    "CLIArg",
    "CLICommand",
    "Cache",
    "CacheEntry",
    "CacheStats",
    "Change",
    "CheckCategory",
    "CheckResult",
    "Color",
    "ComparisonResult",
    "ComplianceIssue",
    "ComplianceReport",
    "ComputeCache",
    "ConfigError",
    "Configurable",
    "ContentExtractionError",
    "ContentPolicy",
    "CredibilityReport",
    "CredibilityScore",
    "CrossRefIndex",
    "CrossRefTarget",
    "DataPipeline",
    "DataValidationResult",
    "Debouncer",
    "DeepResearcher",
    "DeepWormError",
    "DependencyStatus",
    "DeserializationResult",
    "DiagnosticReport",
    "Disposable",
    "DocumentSchema",
    "Edge",
    "EdgeType",
    "Either",
    "EmphasisStyle",
    "EnvironmentInfo",
    "Err",
    "ErrorStrategy",
    "Event",
    "EventEmitter",
    "EventType",
    "EvictionPolicy",
    "ExportFormat",
    "ExportOptions",
    "ExportResult",
    "FieldType",
    "FixedWindow",
    "FootnoteResult",
    "Format",
    "FormatOptions",
    "FormatResult",
    "Glossary",
    "GlossaryEntry",
    "GraphStats",
    "HealthStatus",
    "HistoryEntry",
    "HookContext",
    "HookEntry",
    "HookRegistry",
    "HookResult",
    "HookStage",
    "Identifiable",
    "IssueCategory",
    "KeyedRateLimiter",
    "Keyword",
    "KeywordResult",
    "KnowledgeGraph",
    "Language",
    "LanguageDetection",
    "Lazy",
    "Left",
    "LimitAction",
    "LimiterStrategy",
    "ListStyle",
    "MiddlewareEntry",
    "MiddlewarePhase",
    "MiddlewareStack",
    "MockCall",
    "MockFunction",
    "MockSequence",
    "ModelNotFoundError",
    "NOTHING",
    "NetworkError",
    "Node",
    "Nothing",
    "NotionBlock",
    "NotionPage",
    "Ok",
    "Once",
    "Option",
    "OutlineSection",
    "OutputFormat",
    "Pair",
    "Pipeline",
    "PipelineBatchResult",
    "PipelineResult",
    "PipelineStatus",
    "PoolStats",
    "ProfileResult",
    "Profiler",
    "ProgressBar",
    "ProgressSnapshot",
    "ProgressTracker",
    "ProviderError",
    "QualityScore",
    "RateLimitError",
    "RateLimitExceeded",
    "RateLimitInfo",
    "RateLimitStats",
    "ReadabilityResult",
    "Reference",
    "Renderable",
    "RenderResult",
    "ReportOutline",
    "Request",
    "RequestLog",
    "RequestLogger",
    "RequestMethod",
    "ResearchPlan",
    "ResearchStage",
    "Response",
    "Result",
    "ResultStatus",
    "Revision",
    "RevisionDiff",
    "RevisionHistory",
    "Right",
    "SchemaField",
    "SchemaValidationError",
    "SchemaValidationResult",
    "SearchError",
    "SectionRule",
    "SecurityFinding",
    "SecurityReport",
    "SentimentReport",
    "SentimentScore",
    "Serializable",
    "SerializationResult",
    "SessionError",
    "Severity",
    "SimilarityResult",
    "SlidingWindow",
    "Snapshot",
    "SnapshotStore",
    "Some",
    "Spinner",
    "Stage",
    "StageResult",
    "StageStatus",
    "StyleGuide",
    "Summary",
    "TableAlignment",
    "TableOfContents",
    "Task",
    "TaskQueue",
    "TaskResult",
    "TaskStatus",
    "TemplateContext",
    "TemplateError",
    "TestFixture",
    "TextStatistics",
    "ThreatLevel",
    "ThreatType",
    "Throttle",
    "TieredCache",
    "Timeline",
    "TimelineEvent",
    "TimingResult",
    "TocEntry",
    "Token",
    "TokenBucket",
    "TokenType",
    "ToneAnalysis",
    "TransformChain",
    "TransformChainResult",
    "TransformResult",
    "TransformType",
    "TranslationCatalog",
    "TranslationEntry",
    "Validatable",
    "ValidationResult",
    "ValidationRule",
    "Verbosity",
    "WordCloudData",
    "WordFrequency",
    "WorkerPool",
    "WorkerState",
    "__version__",
    "academic_style_guide",
    "add_footnotes",
    "add_heading_ids",
    "add_language_labels",
    "analyze_readability",
    "analyze_report_sentiment",
    "analyze_sentiment",
    "analyze_tone",
    "annotate_report",
    "article_schema",
    "assert_contains_all",
    "assert_fast",
    "assert_json_valid",
    "assert_markdown_valid",
    "assert_no_duplicates",
    "assert_word_count_range",
    "async_research",
    "auth_middleware",
    "auto_annotate",
    "batch_export",
    "batch_process",
    "blue",
    "bold",
    "build_crossref_index",
    "cache_key",
    "check_compliance",
    "check_dependencies",
    "check_path_traversal",
    "chunk",
    "cleanup_transform",
    "collect_environment",
    "colorize",
    "compare_statistics",
    "compare_texts",
    "compare_timelines",
    "compare_word_clouds",
    "comparison_template",
    "compute_diff",
    "compute_statistics",
    "constant_time_compare",
    "content_hash",
    "content_type_middleware",
    "convert",
    "cosine_similarity",
    "create_atomic",
    "create_audit_log",
    "create_batch",
    "create_cache",
    "create_catalog",
    "create_compute_cache",
    "create_context",
    "create_counter",
    "create_data_pipeline",
    "create_fixture",
    "create_fixed_window",
    "create_format_options",
    "create_graph",
    "create_history",
    "create_keyed_limiter",
    "create_logger",
    "create_middleware",
    "create_middleware_stack",
    "create_mock",
    "create_pipeline",
    "create_profiler",
    "create_progress_bar",
    "create_reference",
    "create_request",
    "create_response",
    "create_revision",
    "create_schema",
    "create_sequence",
    "create_sliding_window",
    "create_snapshot_store",
    "create_spinner",
    "create_style_guide",
    "create_task_queue",
    "create_tiered_cache",
    "create_timeline",
    "create_token_bucket",
    "create_transform_chain",
    "create_validation_rule",
    "create_worker_pool",
    "cyan",
    "detect_format",
    "detect_language",
    "detect_pii",
    "detect_plagiarism",
    "detect_secrets",
    "dim",
    "distinct",
    "draw_box",
    "ensure_blank_lines_around_headings",
    "err",
    "estimate_complexity",
    "export_notion_json",
    "export_report",
    "extract_annotations",
    "extract_concept_graph",
    "extract_glossary",
    "extract_key_findings",
    "extract_keywords",
    "extract_link_graph",
    "extract_references",
    "extract_section",
    "extract_tags",
    "extract_timeline",
    "extract_toc",
    "extract_topics",
    "extract_translatable",
    "extract_urls",
    "extract_variables",
    "fan_in",
    "fan_out",
    "filter_data",
    "find_replace",
    "find_replace_batch",
    "find_similar",
    "fix_indentation",
    "flatten",
    "format_document",
    "format_duration",
    "format_help",
    "format_key_value",
    "format_list",
    "format_percentage",
    "format_size",
    "format_table",
    "format_table_simple",
    "from_csv",
    "from_json",
    "from_markdown_table",
    "from_xml",
    "from_yaml",
    "generate_list_of_figures",
    "generate_list_of_tables",
    "generate_outline",
    "generate_plan",
    "generate_toc",
    "generate_token",
    "generate_word_cloud",
    "get_global_registry",
    "get_language",
    "green",
    "group_by",
    "header_injection",
    "hook",
    "indent_text",
    "inject_bibliography",
    "inject_crossrefs",
    "inject_glossary",
    "inject_toc",
    "is_callable",
    "is_dict_like",
    "is_list_like",
    "is_non_empty_string",
    "is_numeric",
    "is_renderable",
    "is_serializable",
    "is_validatable",
    "left",
    "list_filters",
    "list_languages",
    "map_data",
    "markdown_to_notion",
    "mask_secret",
    "memoize",
    "merge_bibliographies",
    "merge_catalogs",
    "merge_footnotes",
    "merge_graphs",
    "merge_revisions",
    "merge_tocs",
    "minify_json",
    "minimal_audit_policy",
    "normalize_blockquotes",
    "normalize_code_fences",
    "normalize_emphasis",
    "normalize_headings",
    "normalize_links",
    "normalize_lists",
    "normalize_whitespace",
    "nothing",
    "ok",
    "outline_from_report",
    "pad_left",
    "pad_right",
    "pair",
    "parallel_map",
    "parse_args",
    "pretty_json",
    "quick_check",
    "rate_limit",
    "reading_level",
    "red",
    "redact_text",
    "reduce_data",
    "relaxed_policy",
    "remove_section",
    "render_template",
    "renumber_footnotes",
    "reorder_sections",
    "report_schema",
    "report_template",
    "research",
    "research_chain",
    "retry_middleware",
    "right",
    "run_batch",
    "run_diagnostics",
    "safe_bool",
    "safe_float",
    "safe_int",
    "safe_str",
    "sample_config",
    "sample_markdown",
    "sample_research_data",
    "sanitize_html",
    "sanitize_markdown",
    "scan_content",
    "score_report",
    "score_source",
    "score_sources",
    "section_statistics",
    "self_test",
    "sentiment_diff",
    "serialize",
    "some",
    "sort_list",
    "strict_audit_policy",
    "strict_policy",
    "strip_comments",
    "strip_footnotes",
    "strip_html",
    "summarize",
    "supports_color",
    "technical_style_guide",
    "tfidf_cloud",
    "time_execution",
    "timeout_middleware",
    "to_csv",
    "to_json",
    "to_markdown_table",
    "to_sentence_case",
    "to_title_case",
    "to_xml",
    "to_yaml",
    "track_changes",
    "truncate",
    "try_result",
    "user_agent_middleware",
    "validate_data",
    "validate_template",
    "validate_topic",
    "validate_url",
    "vocabulary_analysis",
    "wrap_text",
    "yellow",
]

# Set up default logging (NullHandler to avoid "No handlers" warnings)
logging.getLogger("deepworm").addHandler(logging.NullHandler())


def research(topic: str, **kwargs) -> str:
    """Quick research function. Returns a markdown report.

    Usage:
        from deepworm import research
        report = research("quantum computing advances in 2024")
    """
    researcher = DeepResearcher(**kwargs)
    return researcher.research(topic)