"""Plugin system for extending deepworm.

Hooks allow users to customize the research pipeline without
modifying the core code. Plugins can filter sources, transform
queries, modify reports, and add custom analysis steps.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

logger = logging.getLogger(__name__)


@dataclass
class HookResult:
    """Result from a hook call. Can modify or skip data."""
    data: Any = None
    skip: bool = False  # If True, skip the current item


# Hook function types
QueryHook = Callable[[str, list[str]], list[str]]  # (topic, queries) -> queries
SourceFilterHook = Callable[[str, str, str], bool]  # (url, title, content) -> keep?
AnalysisHook = Callable[[str, str, str], str]  # (topic, source_text, findings) -> findings
ReportHook = Callable[[str, str], str]  # (topic, report) -> report


class PluginManager:
    """Manages hook-based plugins for the research pipeline.

    Usage:
        pm = PluginManager()

        @pm.hook("filter_source")
        def skip_paywalls(url, title, content):
            return "paywall" not in content.lower()

        @pm.hook("transform_queries")
        def add_year(topic, queries):
            return [f"{q} 2024" for q in queries]

        @pm.hook("post_report")
        def add_disclaimer(topic, report):
            return report + "\\n\\n*Generated by AI. Verify facts independently.*"
    """

    def __init__(self):
        self._hooks: dict[str, list[Callable]] = {
            "transform_queries": [],
            "filter_source": [],
            "post_analysis": [],
            "post_report": [],
            "pre_search": [],
            "post_search": [],
        }

    def hook(self, name: str) -> Callable:
        """Decorator to register a hook function.

        Available hooks:
            transform_queries(topic, queries) -> queries
            filter_source(url, title, content) -> bool
            post_analysis(topic, source_text, findings) -> findings
            post_report(topic, report) -> report
            pre_search(query) -> query
            post_search(query, results) -> results
        """
        if name not in self._hooks:
            raise ValueError(
                f"Unknown hook: {name}. Available: {', '.join(self._hooks.keys())}"
            )

        def decorator(func: Callable) -> Callable:
            self._hooks[name].append(func)
            return func

        return decorator

    def register(self, name: str, func: Callable) -> None:
        """Register a hook function (non-decorator form)."""
        if name not in self._hooks:
            raise ValueError(f"Unknown hook: {name}")
        self._hooks[name].append(func)

    def apply_transform_queries(self, topic: str, queries: list[str]) -> list[str]:
        """Apply all transform_queries hooks."""
        result = queries
        for hook in self._hooks["transform_queries"]:
            try:
                result = hook(topic, result)
            except Exception as e:
                logger.warning("Hook transform_queries failed: %s", e)
        return result

    def apply_filter_source(self, url: str, title: str, content: str) -> bool:
        """Apply all filter_source hooks. Returns False if any hook rejects."""
        for hook in self._hooks["filter_source"]:
            try:
                if not hook(url, title, content):
                    logger.debug("Source filtered by hook: %s", url[:80])
                    return False
            except Exception as e:
                logger.warning("Hook filter_source failed: %s", e)
        return True

    def apply_post_analysis(self, topic: str, source_text: str, findings: str) -> str:
        """Apply all post_analysis hooks."""
        result = findings
        for hook in self._hooks["post_analysis"]:
            try:
                result = hook(topic, source_text, result)
            except Exception as e:
                logger.warning("Hook post_analysis failed: %s", e)
        return result

    def apply_post_report(self, topic: str, report: str) -> str:
        """Apply all post_report hooks."""
        result = report
        for hook in self._hooks["post_report"]:
            try:
                result = hook(topic, result)
            except Exception as e:
                logger.warning("Hook post_report failed: %s", e)
        return result

    def apply_pre_search(self, query: str) -> str:
        """Apply all pre_search hooks."""
        result = query
        for hook in self._hooks["pre_search"]:
            try:
                result = hook(result)
            except Exception as e:
                logger.warning("Hook pre_search failed: %s", e)
        return result

    def apply_post_search(self, query: str, results: list) -> list:
        """Apply all post_search hooks."""
        result = results
        for hook in self._hooks["post_search"]:
            try:
                result = hook(query, result)
            except Exception as e:
                logger.warning("Hook post_search failed: %s", e)
        return result

    def clear(self, name: str | None = None) -> None:
        """Clear hooks. If name is None, clear all."""
        if name:
            self._hooks[name] = []
        else:
            for key in self._hooks:
                self._hooks[key] = []

    @property
    def registered_hooks(self) -> dict[str, int]:
        """Return count of registered hooks per type."""
        return {k: len(v) for k, v in self._hooks.items() if v}
