"""Report formatting and output utilities."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.markdown import Markdown


console = Console()


def print_report(report: str) -> None:
    """Print a markdown report to the terminal with rich formatting."""
    md = Markdown(report)
    console.print()
    console.print(md)
    console.print()


def save_report(
    report: str,
    path: str | None = None,
    topic: str = "",
    fmt: str = "markdown",
) -> str:
    """Save a report to a file. Returns the path used.

    Formats: markdown (default), text, json, html, pdf
    """
    if path is None:
        slug = _slugify(topic) if topic else "research"
        ext = {
            "markdown": ".md", "text": ".txt", "json": ".json",
            "html": ".html", "pdf": ".pdf",
        }.get(fmt, ".md")
        path = f"{slug}{ext}"

    filepath = Path(path)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    if fmt == "json":
        data = {"topic": topic, "report": report}
        filepath.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    elif fmt == "text":
        plain = _markdown_to_text(report)
        filepath.write_text(plain, encoding="utf-8")
    elif fmt == "html":
        html = markdown_to_html(report, topic=topic)
        filepath.write_text(html, encoding="utf-8")
    elif fmt == "pdf":
        _save_pdf(report, filepath, topic=topic)
    else:
        filepath.write_text(report, encoding="utf-8")

    return str(filepath)


def markdown_to_html(md: str, topic: str = "") -> str:
    """Convert markdown report to a standalone HTML document.

    Uses a built-in markdown-to-HTML converter (no external dependencies).
    Includes responsive CSS styling.
    """
    title = topic or "Research Report"

    # Convert markdown to HTML body
    body = _md_to_html_body(md)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{_escape_html(title)}</title>
    <style>
        :root {{
            --bg: #ffffff;
            --text: #1a1a1a;
            --muted: #6b7280;
            --border: #e5e7eb;
            --accent: #2563eb;
            --code-bg: #f3f4f6;
        }}
        @media (prefers-color-scheme: dark) {{
            :root {{
                --bg: #111827;
                --text: #f3f4f6;
                --muted: #9ca3af;
                --border: #374151;
                --accent: #60a5fa;
                --code-bg: #1f2937;
            }}
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.7;
            color: var(--text);
            background: var(--bg);
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem 1.5rem;
        }}
        h1 {{ font-size: 2rem; margin: 1.5rem 0 1rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }}
        h2 {{ font-size: 1.5rem; margin: 1.5rem 0 0.75rem; color: var(--accent); }}
        h3 {{ font-size: 1.2rem; margin: 1.25rem 0 0.5rem; }}
        p {{ margin: 0.75rem 0; }}
        ul, ol {{ margin: 0.75rem 0; padding-left: 1.5rem; }}
        li {{ margin: 0.25rem 0; }}
        a {{ color: var(--accent); text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        code {{
            background: var(--code-bg);
            padding: 0.15em 0.4em;
            border-radius: 4px;
            font-size: 0.9em;
        }}
        pre {{
            background: var(--code-bg);
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
            margin: 1rem 0;
        }}
        pre code {{ background: none; padding: 0; }}
        blockquote {{
            border-left: 4px solid var(--accent);
            padding-left: 1rem;
            margin: 1rem 0;
            color: var(--muted);
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 1rem 0;
        }}
        th, td {{
            border: 1px solid var(--border);
            padding: 0.5rem 0.75rem;
            text-align: left;
        }}
        th {{ background: var(--code-bg); font-weight: 600; }}
        hr {{ border: none; border-top: 1px solid var(--border); margin: 2rem 0; }}
        .footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid var(--border);
            color: var(--muted);
            font-size: 0.85rem;
        }}
    </style>
</head>
<body>
{body}
<div class="footer">
    Generated by <a href="https://github.com/bysiber/deepworm">deepworm</a>
</div>
</body>
</html>"""


def _md_to_html_body(md: str) -> str:
    """Convert markdown text to HTML body (minimal parser, no deps)."""
    lines = md.split("\n")
    html_lines = []
    in_code_block = False
    in_list = False
    list_type = "ul"

    for line in lines:
        # Code blocks
        if line.strip().startswith("```"):
            if in_code_block:
                html_lines.append("</code></pre>")
                in_code_block = False
            else:
                lang = line.strip()[3:].strip()
                html_lines.append(f'<pre><code class="language-{lang}">' if lang else "<pre><code>")
                in_code_block = True
            continue

        if in_code_block:
            html_lines.append(_escape_html(line))
            continue

        # Close list if needed
        if in_list and not re.match(r'^(\s*[-*+]|\s*\d+\.)\s', line) and line.strip():
            html_lines.append(f"</{list_type}>")
            in_list = False

        # Headers
        header_match = re.match(r'^(#{1,6})\s+(.+)', line)
        if header_match:
            level = len(header_match.group(1))
            text = _inline_md(header_match.group(2))
            html_lines.append(f"<h{level}>{text}</h{level}>")
            continue

        # Horizontal rules
        if re.match(r'^(-{3,}|\*{3,}|_{3,})\s*$', line):
            html_lines.append("<hr>")
            continue

        # Unordered lists
        ul_match = re.match(r'^(\s*)[-*+]\s+(.+)', line)
        if ul_match:
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
                list_type = "ul"
            html_lines.append(f"<li>{_inline_md(ul_match.group(2))}</li>")
            continue

        # Ordered lists
        ol_match = re.match(r'^(\s*)\d+\.\s+(.+)', line)
        if ol_match:
            if not in_list:
                html_lines.append("<ol>")
                in_list = True
                list_type = "ol"
            html_lines.append(f"<li>{_inline_md(ol_match.group(2))}</li>")
            continue

        # Blockquotes
        if line.startswith(">"):
            text = _inline_md(line.lstrip("> "))
            html_lines.append(f"<blockquote><p>{text}</p></blockquote>")
            continue

        # Table rows
        if "|" in line:
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if cells and all(re.match(r'^[-:]+$', c) for c in cells):
                continue  # Skip separator row
            if cells:
                is_first_row = not any("<tr>" in l for l in html_lines[-10:])
                tag = "th" if is_first_row else "td"
                if is_first_row:
                    html_lines.append("<table>")
                row = "".join(f"<{tag}>{_inline_md(c)}</{tag}>" for c in cells)
                html_lines.append(f"<tr>{row}</tr>")
                continue

        # Empty lines
        if not line.strip():
            html_lines.append("")
            continue

        # Regular paragraph
        html_lines.append(f"<p>{_inline_md(line)}</p>")

    # Close any open elements
    if in_list:
        html_lines.append(f"</{list_type}>")
    if in_code_block:
        html_lines.append("</code></pre>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline markdown (bold, italic, code, links) to HTML."""
    # Code (must be first to avoid processing inside code)
    text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'__(.+?)__', r'<strong>\1</strong>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)
    text = re.sub(r'_(.+?)_', r'<em>\1</em>', text)
    # Links
    text = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', text)
    # Images
    text = re.sub(r'!\[(.+?)\]\((.+?)\)', r'<img src="\2" alt="\1">', text)
    return text


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _markdown_to_text(md: str) -> str:
    """Basic markdown to plain text conversion."""
    text = md
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    text = re.sub(r'```.*?```', '', text, flags=re.DOTALL)
    text = re.sub(r'`(.+?)`', r'\1', text)
    return text


def _save_pdf(report: str, path: Path, topic: str = "") -> None:
    """Save report as PDF.

    Attempts to use ``weasyprint`` if installed, otherwise falls back to
    saving a print-optimized HTML file with a ``.pdf.html`` extension and
    a helpful message.
    """
    html_content = markdown_to_html(report, topic=topic)

    # Inject print-friendly CSS overrides
    print_css = """
    <style>
        @media print {
            body { background: white; color: black; }
            .container { max-width: 100%; padding: 0; }
            a { color: black; text-decoration: underline; }
            pre { white-space: pre-wrap; border: 1px solid #ccc; }
        }
        @page {
            size: A4;
            margin: 2cm;
        }
    </style>
    """
    html_content = html_content.replace("</head>", print_css + "</head>")

    try:
        import weasyprint  # type: ignore[import-untyped]

        weasyprint.HTML(string=html_content).write_pdf(str(path))
    except ImportError:
        # Fallback: save as HTML that can be printed to PDF
        html_path = str(path) + ".html"
        Path(html_path).write_text(html_content, encoding="utf-8")
        # Also create a minimal PDF with just text using reportlab if available
        try:
            _create_text_pdf(report, path)
        except ImportError:
            # Last resort: rename the file to indicate it's HTML
            import shutil
            shutil.move(html_path, str(path))
            import logging
            logging.getLogger("deepworm").info(
                "Saved as HTML (install 'weasyprint' for true PDF: pip install weasyprint)"
            )


def _create_text_pdf(text: str, path: Path) -> None:
    """Create a basic PDF using reportlab (if available)."""
    from reportlab.lib.pagesizes import A4  # type: ignore[import-untyped]
    from reportlab.lib.styles import getSampleStyleSheet  # type: ignore[import-untyped]
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer  # type: ignore[import-untyped]

    doc = SimpleDocTemplate(str(path), pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 12))
            continue

        if line.startswith("# "):
            story.append(Paragraph(line[2:], styles["Heading1"]))
        elif line.startswith("## "):
            story.append(Paragraph(line[3:], styles["Heading2"]))
        elif line.startswith("### "):
            story.append(Paragraph(line[4:], styles["Heading3"]))
        elif line.startswith("- ") or line.startswith("* "):
            story.append(Paragraph(f"• {line[2:]}", styles["Normal"]))
        else:
            # Basic markdown cleanup
            cleaned = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', line)
            cleaned = re.sub(r'\*(.+?)\*', r'<i>\1</i>', cleaned)
            cleaned = re.sub(r'`(.+?)`', r'<font face="Courier">\1</font>', cleaned)
            cleaned = re.sub(r'\[(.+?)\]\((.+?)\)', r'\1', cleaned)
            story.append(Paragraph(cleaned, styles["Normal"]))

    doc.build(story)


def _slugify(text: str) -> str:
    """Convert text to a filesystem-safe slug."""
    text = text.lower().strip()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text)
    text = re.sub(r'-+', '-', text)
    return text[:60].strip('-')
